---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuard
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    cert-manager.io/cluster-issuer: "letsencrypt"
    acme.cert-manager.io/http01-ingress-class: "public-nginx"
spec:
  tls:
  - hosts:
    - kuard.k3s.endersgame.net
    secretName: quickstart-example-tls
  rules:
  - host: kuard.k3s.endersgame.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kuard
            port:
              number: 80
