---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: banzaicloud-stable
  namespace: flux-system
spec:
  interval: 30m
  url: https://kubernetes-charts.banzaicloud.com
  timeout: 2m
