---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
  name: vault-tls
spec:
  commonName: vault.k3s.vm.endersgame.net
  dnsNames:
  - vault.k3s.vm.endersgame.net
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: vault-tls
