# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:160OOz2YibDrtmwi9isQ/qJi,iv:5ADHAd6ii92AaGJYOwbOl78+WC2e7B5ulJDV/2kRfHA=,tag:TN2yFR8e2vF8lPUUIkHegw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:9uALxnnJ2qme2WKXsvMXeCQw,iv:oOkYJ3jkvXtDmMcN0wtLftD80/O9NY3rOSkcanWu2H0=,tag:sGHU/eWZKKq4jmEA6fCEkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-10T01:22:08Z"
    mac: ENC[AES256_GCM,data:5VzsvbNEMnxXhGU8TyGZ8xoNSCxrdPgmL99mLF5GbcCK79kXe8gPY5WpDOv9EXH/CEiF0RI3uwY7WErxaK7a+eRSE6SqpLsYB4SVdjjH4LtaMhv5JxfYcSL/XTHYrYp5eRsu9B4P7c7PICwANXM7RIdsyroEL7S4D9HuSqXfmLA=,iv:cgYtiOqce/Fk5OGLrS19Mz9h8WXXVgFyOwbAiaQes1Y=,tag:8EnN2KUyTnarIoGfBH017w==,type:str]
    pgp:
        - created_at: "2021-05-10T01:22:06Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA424sIoUwW0xAQ/+IYhIcXNZsrGWvLTJbqLeTuYFm3GBowPn6MH1MsJ0wn4G
            dNCPC06yf1xk279EtiG59Z4AtvY28wagJr9QLoyx8hw1j90PUX3ichlSP7Kpkh2S
            fc79hGHU70lFKneVnjrs2HI2JNrJgEEcPJOulHLvIFEXyQFzPMl+snkyk/uhZ4tD
            /RS+8Y2MALT9s8Z+JFoLJCiMVeQ38fxoNHPFU4C0VieeNoADcAxhk1VP6tcUTqZz
            vbkpHHpm21ljRR4lL6C2IM/l3f7Akvb511D/Ms62h98ULvP9MD2AcFwNiqDMhMQ3
            XjEOaCS5Sytrh/cAhp68dfcOEABF60xWpLfNk1Awk03U9z2I2IV7x+NGiYVHyKcp
            NtBJ5kW93p1jxIy9+rKRJi0DsggU5+svBeoL1hfqVfE1xWbMQrbWoz8tsE5DHU4L
            vdNfiFTZFWPz50g9elGRXCL8iCIRM4o26heGBosV+ItFgf6dL/W2gb21dk3qAlUM
            hSRQwpH9Owl/SJqnXe9TAqS4pUECyjtGmvuKmsn9phmuGToh4Vkcr+gFpZ5xdW4i
            ZGveoIEI00kCD1J4dfLtxLHtELTTbdRWfNUFR0fh0tgc6wkLO7QOeCrqvTqW8HwJ
            gRqCnRnQy612Pyw9GTsFvy8cYDFvL3XhNua2GbmMhW8yf4QslwVLKm0ooGJtNmLS
            XAGuhPL4WuOoDz7fUc55j8B+jhK5mOqr05ZDrQCY70jHIqWZqC6XiAnM/KGPXDiL
            M9kbqCzwXxCMM7h2GA2DwJhmmAWGQNqTkFGW14cSGfXTqGbHVTn+OMJcegrM
            =B2bV
            -----END PGP MESSAGE-----
          fp: A3033EC08A64896AF5EBAA4D8CB6A612BAF7AAC1
        - created_at: "2021-05-10T01:22:06Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1XRrEFq6hQJARAA0WOq4Hf5V0yKVHYQXDTvXW+f70yVn+4tktgVBg8+MtI+
            qMk/LGXUCBt7Ntl+Wv2eLa9hzGHyBCPKTTGHA9R6s7eZpRcMR8O153N3moKUyT+2
            Ck9+1JEyDkfcj+EAiDIT1FXe/avC+TDwyVfhZfsMJJKV0NkspHrKwfiyzJVr5lYc
            j48g575tO2YtZJT4HA1mTU4/kGjuZ6/94DnTJp137dnlsyw5bQnq+GigKPW5WZgn
            PZEHJXgAqOp+lsJvE4dIDvoiGtEmt28qGUZOCGHr//l+Zk/H3B3KatxSGB8WUHvJ
            Qvcdjt/nc1AiZPwrizwVLEmEh1SgM7OoVqXXSa1JuFmuJvqcNWk6fhyINBHGxIvW
            kqqW3iD9LjysKAC5u3cf7Hra3lfsOXRKM1wXwkGmGA/pVi+CR642AMzOV3HA8KaK
            fkdLV8bgNVm79y+9379VvwTpt/KnBDSL6jjJiPzvd00PDh/dQFv6CEIrtGs7Eoiq
            a8Igaw773ZtLmNkKGap9DpjgZeHHG3Pm04aVZpkBaExAV9c97AbwhdJo371vNHz5
            H/RbESoPbl7ygV4cc/LDh2MbDYLrjo0s/I5ZchDa5z4K2fB1gVwqR/j9PZainrM1
            ttSaR2CXOvV37KXAsB3E4TOyxCNYPGY6D2T13h18LnYDA4+jhrjEbe8VUE03Bo7S
            XAH90ljC2s2XQtLppwasvwYvDbjxYE4VWcbG8lERhkap+ObyltD4pcW8OzRuPjdZ
            rDeRaP7EVT0s9HRNUt7pFQiCw1AXqLEkCy7qpe8kQHYcmc7VFGhtZ1IRJTmB
            =cqTj
            -----END PGP MESSAGE-----
          fp: 0167CBD7C5BCA83BAA77862A689D9103A28DA579
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
