---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  ingress_type: Ingress
  hostname: awx.k3s.endersgame.net
  web_resource_requirements:
    requests:
      cpu: 1000m
      memory: 2Gi
  task_resource_requirements:
    requests:
      cpu: 500m
      memory: 1Gi
  ee_resource_requirements:
    requests:
      cpu: 500m
      memory: 1Gi
