apiVersion: apps/v1
kind: Deployment
metadata:
    name: awx-operator
spec:
    replicas: 1
    selector:
        matchLabels:
            name: awx-operator
    template:
        metadata:
            labels:
                name: awx-operator
        spec:
            containers:
                - env:
                    - name: WATCH_NAMESPACE
                      value: ""
                    - name: POD_NAME
                      valueFrom:
                        fieldRef:
                            fieldPath: metadata.name
                    - name: OPERATOR_NAME
                      value: awx-operator
                    - name: ANSIBLE_GATHERING
                      value: explicit
                  image: quay.io/ansible/awx-operator:0.9.0
                  imagePullPolicy: Always
                  livenessProbe:
                    httpGet:
                        path: /healthz
                        port: 6789
                    initialDelaySeconds: 15
                    periodSeconds: 20
                  name: awx-operator
                  volumeMounts:
                    - mountPath: /tmp/ansible-operator/runner
                      name: runner
            serviceAccountName: awx-operator
            volumes:
                - emptyDir: {}
                  name: runner
