---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: awx
resources:
- customresourcedefinition-awxs.awx.ansible.com.yaml
- customresourcedefinition-awxsbackups.awx.ansible.com.yaml
- customresourcedefinition-awxsrestores.awx.ansible.com.yaml
